//
//  _7_2_main_4_try_catch.m
//  test-Object-C
//
//  Created by hades on 2021/7/6.
//  Copyright Â© 2021 hades. All rights reserved.
//

#import <Foundation/Foundation.h>

/*int main(int argc, const char* argv[]){
    @autoreleasepool {
        NSArray *array = [[NSArray alloc]init];
        @try {
            NSLog(@"%@",[array objectAtIndex:0]);
        }
        @catch (NSException *exception) {
            // catch: NSRangeException,*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
            NSLog(@"catch: %@,%@",[exception name],[exception reason]);
        }
        @finally {
            NSLog(@"finally");
        }
        NSLog(@"Execution continues");
        
//        NSException *e = [NSException exceptionWithName:@"Exception:" reason:@"test throw " userInfo:nil];
//        @throw e;
        // *** Terminating app due to uncaught exception 'Exception:', reason: 'test throw '
    }
    return 0;
}
*/
